version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: web

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - db
    container_name: php

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    restart: always
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "laravel"
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: db

  # redis:
  #   image: redis:6-alpine
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   container_name: dating_redis

  # echo-server:
  #   image: oanhnn/laravel-echo-server:latest
  #   ports:
  #     - 6001:6001
  #   tty: true
  #   environment:
  #     LARAVEL_ECHO_SERVER_DEBUG: 'true'
  #     LARAVEL_ECHO_SERVER_DB: redis
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_DB: 0
  #   container_name: echo_server
  #   depends_on:
  #     - redis
  #   volumes:
  #   - ./docker/echo_server/laravel-echo-server.json:/app/laravel-echo-server.json
  #   restart: unless-stopped

  mail:
    image: mailhog/mailhog
    user: root
    restart: always
    tty: true
    privileged: true
    ports:
      - 1025:1025
      - 8025:8025
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    volumes:
      - mail_data:/maildir
    container_name: mail

  npm:
    image: node:12-alpine
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    container_name: npm
    profiles: ["ignore"]

  artisan:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ["php", "/var/www/html/artisan"]
    container_name: artisan
    profiles: [ "ignore" ]

  composer:
    image: composer:1.10.22
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer", "--ignore-platform-reqs"]
    container_name: composer
    profiles: [ "ignore" ]

  # phpstan:
  #   image: php:fpm-alpine
  #   volumes:
  #     - ./src/:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ["vendor/bin/phpstan"]
  #   container_name: phpstan
  #   profiles: [ "ignore" ]

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  mail_data:
    driver: local
