version: '3'
services:
  laravel:
    build:
      context: .
    container_name: laravel
    depends_on:
      - db
    volumes:
      - ./src:/app

  web:
    image: nginx
    container_name: web
    depends_on:
      - laravel
    environment:
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=80
      - NGINX_MAX_BODY=100M
      - NGINX_LARAVEL_HOST=laravel
      - NGINX_WEBSOCKET_HOST=herocast-sockets
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/app
      - ./configs/vhost.template:/etc/nginx/conf.d/vhost.template

  db:
    image: mariadb:10.2
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  # redis:
  #   container_name: redis
  #   image: 'redis:alpine'

  # beanstalk:
  #   container_name: beanstalk
  #   image: 'jonbaldie/beanstalkd'


  # Queue Example
  # queue:
  #   image: php:fpm-alpine
  #   container_name: queue
  #   depends_on:
  #     - beanstalk
  #     - redis
  #     - db
  #   command: php /app/artisan queue:work --tries=2 --timeout=150
  #   volumes:
  #     - ./src:/app

  # Scheduler Example
  # scheduler:
  #   image: php:fpm-alpine
  #   container_name: scheduler
  #   depends_on:
  #     - beanstalk
  #     - redis
  #     - db
  #   command: sh -c "cd /app && while true; do sleep 60 && php artisan schedule:run; done"
  #   volumes:
  #     - ./src:/app

volumes:
  db_data:
