#!/bin/bash
#
# Initialize Laravel project for first usage.
#

# STDERR log function
err() {
  echo -e "\n[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@\n" >&2
  exit 1
}

# STDOUT log function
log() {
  echo -e "\n[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@\n"
}

# Check if Docker is installed
if ! type "docker" > /dev/null 2>&1; then
    err "Docker not installed"
fi

# Check if Docker-compose is installed
if ! type "docker-compose" > /dev/null 2>&1; then
    err "Docker-Compose not installed"
fi
log "Looks like both docker and docker-compose are installed, everything looks good."

log "Copying .env.example -> .env"
cp ./src/.env.example ./src/.env
if [ $? -ne 0 ]; then
    err "Error while copying .env"
fi

log "Removing previous volumes"
docker-compose down -v
log "Starting docker-compose stack..."
docker-compose up -d
if [ $? -ne 0 ]; then
    err "Error while starting docker-compose stack."
fi

log "Installing dependencies"
docker-compose run --rm composer install
if [ $? -ne 0 ]; then
    err "Error while installing dependencies."
fi

log "Generating app key"
docker-compose run --rm artisan key:generate && \
docker-compose run --rm artisan cache:clear
if [ $? -ne 0 ]; then
    err "Error while generating app key."
fi

log "Running database migrations"
docker-compose run --rm artisan migrate
if [ $? -ne 0 ]; then
    err "Error while running database migrations."
fi

# log "Installing npm packages"
# docker-compose run --rm npm install
# if [ $? -ne 0 ]; then
#     err "Error while installing npm packages."
# fi

# log "Compiling assets."
# docker-compose run --rm npm run dev
# if [ $? -ne 0 ]; then
#     err "Error while compiling assets."
# fi

log "Copying the pre commit hook"
cp pre-commit .git/hooks/pre-commit

log "Finished."
